name: Deploy WinAI to VM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup SSH key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
        
    - name: Add VM to known hosts
      run: |
        ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts
        
    - name: Deploy to VM
      env:
        VM_HOST: ${{ secrets.VM_HOST }}
        VM_USER: ${{ secrets.VM_USER }}
        LETSENCRYPT_EMAIL: ${{ secrets.LETSENCRYPT_EMAIL }}
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        ssh $VM_USER@$VM_HOST << EOF
          # Stop existing containers if they exist
          if [ -d "/home/azureuser/winai" ]; then
            cd /home/azureuser/winai
            sudo docker-compose down || true
          fi
          
          # Create app directory (without sudo since it's in user home)
          mkdir -p /home/azureuser/winai
          cd /home/azureuser/winai
          
          # Clone or pull latest code (without sudo for user directory)
          if [ -d ".git" ]; then
            git remote set-url origin https://${PAT_TOKEN}@github.com/${{ github.repository }}.git
            git fetch origin main
            git reset --hard origin/main
          else
            git clone https://${PAT_TOKEN}@github.com/${{ github.repository }}.git .
          fi
          
          # Update email in docker-compose.yml
          sed -i "s/your-email@example.com/\$LETSENCRYPT_EMAIL/g" docker-compose.yml
          
          # Create SSL directory
          mkdir -p ssl
          
          # Start services
          sudo docker-compose up -d
          
          # Wait for services to be ready
          echo "Waiting for services to start..."
          sleep 30
          
          # Check if we need to get SSL certificate
          if [ ! -f "ssl/live/winai.hiretechteam.ai/fullchain.pem" ]; then
            echo "Getting SSL certificate..."
            sudo docker-compose run --rm certbot
            sudo docker-compose restart nginx
          fi
          
          # Show status
          sudo docker-compose ps
          
          echo "Deployment completed successfully!"
        EOF
        
    - name: Verify deployment
      env:
        VM_HOST: ${{ secrets.VM_HOST }}
        VM_USER: ${{ secrets.VM_USER }}
      run: |
        ssh $VM_USER@$VM_HOST << 'EOF'
          cd /home/azureuser/winai
          echo "=== Service Status ==="
          sudo docker-compose ps
          
          echo "=== Checking health endpoint ==="
          curl -f http://localhost/health || echo "Health check failed (normal if SSL cert is required)"
          
          echo "=== Recent logs ==="
          sudo docker-compose logs --tail=10
        EOF
