name: Deploy WinAI to VM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup SSH key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
        
    - name: Add VM to known hosts
      run: |
        ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts
        
    - name: Deploy to VM
      env:
        VM_HOST: ${{ secrets.VM_HOST }}
        VM_USER: ${{ secrets.VM_USER }}
        LETSENCRYPT_EMAIL: ${{ secrets.LETSENCRYPT_EMAIL }}
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        ssh $VM_USER@$VM_HOST << EOF
          # Stop existing containers if they exist
          if [ -d "/opt/winai" ]; then
            cd /opt/winai
            sudo docker-compose down || true
          fi
          
          # Clean up and recreate app directory (need sudo for /opt)
          sudo rm -rf /opt/winai
          sudo mkdir -p /opt/winai
          cd /opt/winai
          
          # Clone latest code with PAT token (with sudo for /opt directory)
          sudo git clone https://\${PAT_TOKEN}@github.com/${{ github.repository }}.git .
          
          # Verify files were cloned
          echo "=== Verifying cloned files ==="
          ls -la
          echo "=== Checking docker-compose.yml ==="
          if [ -f "docker-compose.yml" ]; then
            echo "✅ docker-compose.yml found"
          else
            echo "❌ docker-compose.yml NOT found"
            exit 1
          fi
          
          # Update email in docker-compose.yml
          sudo sed -i "s/your-email@example.com/\$LETSENCRYPT_EMAIL/g" docker-compose.yml
          
          # Create SSL directory
          sudo mkdir -p ssl
          
          # Start services
          sudo docker-compose up -d
          
          # Wait for services to be ready
          echo "Waiting for services to start..."
          sleep 30
          
          # Check if we need to get SSL certificate
          if [ ! -f "ssl/live/winai.hiretechteam.ai/fullchain.pem" ]; then
            echo "Getting SSL certificate..."
            sudo docker-compose run --rm certbot
            sudo docker-compose restart nginx
          fi
          
          # Show status
          sudo docker-compose ps
          
          echo "Deployment completed successfully!"
        EOF
        
    - name: Verify deployment
      env:
        VM_HOST: ${{ secrets.VM_HOST }}
        VM_USER: ${{ secrets.VM_USER }}
      run: |
        ssh $VM_USER@$VM_HOST << 'EOF'
          cd /opt/winai
          echo "=== Service Status ==="
          sudo docker-compose ps
          
          echo "=== Checking health endpoint ==="
          curl -f http://localhost/health || echo "Health check failed (normal if SSL cert is required)"
          
          echo "=== Recent logs ==="
          sudo docker-compose logs --tail=10
        EOF
